# CI/CD pipeline for Incident Pulse
name: Deploy to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name:  Build and Deploy to AWS
    runs-on: ubuntu-latest
    steps:
    - name: checkout code from github
      uses: actions/checkout@v4
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: login to ecr
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2 
    - name: build, tag and push docker image to ecr 
      run: |
        docker build -t incident-pulse .
        docker tag incident-pulse:latest ${{steps.login-ecr.outputs.registry}}/incident-pulse:latest
        docker push ${{steps.login-ecr.outputs.registry}}/incident-pulse:latest
    - name : update ecs service to run the latest image
      run  : aws ecs update-service --cluster ${{secrets.ECS_CLUSTER_NAME}} --service ${{secrets.ECS_SERVICE_NAME}}  --force-new-deployment
